apiVersion: v1
kind: Pod
metadata:
  name: aspcore-svc-discovery-app
  labels:
    app: aspcore-svc-discovery-app
spec:
  containers:
  - name: aspcore-svc-discovery-app
    image: aspcore-svc-discovery:20200324T211500
    resources: {}
    ports:
    - containerPort: 80
      name: http
---
kind: Service
apiVersion: v1
metadata:
  name: aspcore-svc-discovery-app
spec:
  selector:
    app: aspcore-svc-discovery-app
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80